# Generated by Django 2.2.6 on 2019-11-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191101_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='open_date',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
    ]
