# Generated by Django 2.2.6 on 2019-11-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(max_length=300),
        ),
    ]
