# Generated by Django 2.2.6 on 2019-10-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='past_job',
            field=models.TextField(),
        ),
    ]
